### PR TITLE
use caseLandmarks() in validateDestinationCases()

### PR DESCRIPTION
**Pull request by lindbrook**

### CODE REVIEW

**Comment by Adrian49** [comment]
Hello Lindbrook

I’m very interested in your cholera project on Github.

However, I struggle to visualise your data as a map.

Could you possibly help me with some examples?

Sincerely

Adrian

 

From: lindbrook ***@***.***> 
Sent: Wednesday, February 14, 2024 4:21 AM
To: lindbrook/cholera ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lindbrook/cholera] use caseLandmarks() in validateDestinationCases() (PR #478)

 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/lindbrook/cholera/pull/478


Commit Summary


*	78332b9 <https://github.com/lindbrook/cholera/pull/478/commits/78332b9308550e0de04c4d6b4204c5a0ed844972>  use caseLandmarks() in validateDestinationCases()


File Changes 


(4 <https://github.com/lindbrook/cholera/pull/478/files>  files)

*	M DESCRIPTION <https://github.com/lindbrook/cholera/pull/478/files#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c>  (4) 
*	M NEWS.md <https://github.com/lindbrook/cholera/pull/478/files#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197ea>  (5) 
*	M R/latlongAuxilliaryFunctions.R <https://github.com/lindbrook/cholera/pull/478/files#diff-58cac523c4089e0a7437ec40c089d4191719b613a68ae83be74a754a7f34bbba>  (2) 
*	M README.md <https://github.com/lindbrook/cholera/pull/478/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5>  (2) 


Patch Links:


*	https://github.com/lindbrook/cholera/pull/478.patch
*	https://github.com/lindbrook/cholera/pull/478.diff

**Comment by lindbrook** [comment]
Is your question about this particular pull request?

**Comment by Adrian49** [comment]
No. I was wondering if you have created an updated Cholera Map.

It would be interesting to compare Snow’s original with yours.

Is that possible?

Sincerely 

Adrian

**Comment by lindbrook** [comment]
I'm not entirely sure what you have in mind. You might need to expand on this. (Perhaps we should we move this conversation to GitHub Discussions, which I'd need to enable, rather than in this pull request thread?)

Two things I've done are 1) import Snow's map and Dodson and Tobler's map into image manipulation software: import tiff or pdf's of the maps into GIMP, Photoshop, etc. and 2) geeoreference the data (add latitude and longitude) so you can use it in GIS software or Google Maps etc. For what it's worth, I'm using QGIS and Open Street Maps.

**Comment by Adrian49** [comment]
I have never been able to access Rusty Dodson’s and Waldo Tobler’s stuff on cholera on the NCGIA site since was written in source code.So, if you have been able to generate a map from the code that would be amazing.I guess what I would like to see is a final cartographic product which incorporates all of the great work you have been doing over the years.I receive all your updates from GitHub but sadly I’m unable to consume it which leaves me frustrated and sad.If we could carry on the this discussion on GitHub that would be amazing.Incidentally, I also use GIMP and QGIS. ATM I’m trying out the g3w-suite to publish some of my QGIS projects as a WebGis service. Perhaps your QGIS Cholera Project might benefit from the application since it is available on GitHum.Just a thought…Sincerely Adrian Sent from my iPhoneOn 16 Feb 2024, at 04:50, lindbrook ***@***.***> wrote:﻿
I'm not entirely sure what you have in mind. You might need to expand on this. (Perhaps we should we move this conversation to GitHub Discussions, which I'd need to enable, rather than in this pull request thread?)
Two things I've done are 1) import Snow's map and Dodson and Tobler's map into image manipulation software: import tiff or pdf's of the maps into GIMP, Photoshop, etc. and 2) geeoreference the data (add latitude and longitude) so you can use it in GIS software or Google Maps etc. For what it's worth, I'm using QGIS and Open Street Maps.

**Comment by lindbrook** [comment]
You should now be able to post your question in "Discussions".

**Pull request merged**
